-- 事故表
CREATE EXTERNAL TABLE IF NOT EXISTS dwd.dwd_base_acd_file(
    ajmc string COMMENT '暂无',
    badw string COMMENT '办案单位',
    balxfs string COMMENT '办案联系方式',
    bar1 string COMMENT '办案人1',
    bar2 string COMMENT '办案人2',
    cclrsj string COMMENT '初次录入时间',
    ccyyfl string COMMENT '事故初查原因分类',
    cljsg string COMMENT '车辆间事故',
    dah string COMMENT '档案号',
    dcsg string COMMENT '单车事故',
    djbh string COMMENT '登记编号',
    dlaqsx string COMMENT '道路安全属性',
    dlaqyhdj string COMMENT '道路安全隐患等级',
    dllx string COMMENT '道路类型',
    dlwlgl string COMMENT '道路物理隔离',
    dlxx string COMMENT '道路线型',
    dsrzs string COMMENT '当事人总数',
    dx string COMMENT '地形',
    dzzb string COMMENT '电子坐标',
    ffjg string COMMENT '分发机关',
    fhsslx string COMMENT '路侧防护设施类型',
    fjdcsl string COMMENT '非机动车数量',
    fsjg string COMMENT '发送机关',
    glbm string COMMENT '管理部门',
    gls string COMMENT '公里数',
    glxzdj string COMMENT '公路行政等级',
    gxsj string COMMENT '更新时间',
    hlzt string COMMENT '后轮状态',
    jbr string COMMENT '经办人',
    jdcsl string COMMENT '机动车数量',
    jdwz string COMMENT '绝对位置',
    jllx string COMMENT '快报记录',
    jskcsj string COMMENT '结束勘查时间',
    jtxhfs string COMMENT '交通信号方式（控制）',
    jyaq string COMMENT '简要案情',
    jyw string COMMENT '校验位',
    kcr1 string COMMENT '勘查人1',
    kcr2 string COMMENT '勘查人2',
    kskcsj string COMMENT '开始勘查时间',
    lbqk string COMMENT '路表情况',
    lh string COMMENT '路号',
    lkldlx string COMMENT '路口路段类型',
    lm string COMMENT '路名',
    lmjg string COMMENT '路面结构',
    lmzk string COMMENT '路面状况',
    lwsglx string COMMENT '路外事故类型',
    ms string COMMENT '米数',
    njd string COMMENT '能见度',
    pzfs string COMMENT '碰撞方式',
    qsrs string COMMENT '轻伤人数',
    rdyyfl string COMMENT '事故认定原因分类',
    rnum string COMMENT '暂无2',
    sb string COMMENT '上报',
    scsjd string COMMENT '上传时间段',
    sdsgdscwz string COMMENT '暂无3',
    sfdxsg string COMMENT '是否典型事故',
    sfty string COMMENT '是否逃逸',
    sgbh string COMMENT '事故编号',
    sgccyy string COMMENT '事故初查原因',
    sgdd string COMMENT '事故地点',
    sgfssj string COMMENT '事故发生时间',
    sglx string COMMENT '事故类型',
    sgrdyy string COMMENT '事故认定原因',
    sgxt string COMMENT '事故形态',
    ssrs string COMMENT '受伤人数',
    ssrs24 string COMMENT '24小时受伤人数',
    ssrs3 string COMMENT '3日内受伤人数',
    ssrs30 string COMMENT '30日内受伤人数',
    ssrs7 string COMMENT '7日内受伤人数',
    sszd string COMMENT '所属中队',
    swrs string COMMENT '当场死亡人数',
    swrs24 string COMMENT '24小时死亡人数',
    swrs3 string COMMENT '3日内死亡人数',
    swrs30 string COMMENT '30日内死亡人数',
    swrs7 string COMMENT '7日内死亡人数',
    swrsq string COMMENT '抢救无效死亡人数',
    swsg string COMMENT '涉外事故1是2否',
    sxxz string COMMENT '所辖乡镇',
    szrs string COMMENT '失踪人数',
    tdyl10 string COMMENT '特大预留10',
    tdyl4 string COMMENT '特大预留4',
    tdyl5 string COMMENT '特大预留5',
    tdyl7 string COMMENT '特大预留7',
    tdyl8 string COMMENT '特大预留8',
    tdyl9 string COMMENT '特大预留9',
    tjr1 string COMMENT '调解人1',
    tjr2 string COMMENT '调解人2',
    tjsgbh string COMMENT '统计事故编号',
    tjsj string COMMENT '提交时间',
    tpzs string COMMENT '图片张数',
    tq string COMMENT '天气',
    tysgzp string COMMENT '逃逸事故侦破',
    tyzpsj string COMMENT '逃逸事故侦破时间',
    xc string COMMENT '现场',
    xctzs string COMMENT '现场图张数',
    xczpzs string COMMENT '现场照片张数',
    xq string COMMENT '星期',
    xrsl string COMMENT '行人数量',
    xzqh string COMMENT '行政区划',
    ylzd4 string COMMENT '预留字段4',
    ylzd5 string COMMENT '预留字段5',
    yzwxp string COMMENT '是否运载危险物品1',
    yzwxphg string COMMENT '运载危险品事故后果',
    zblx string COMMENT '暂无4',
    zhdmwz string COMMENT '在道路横断面位置',
    zjccss string COMMENT '直接财产损失',
    zmtj string COMMENT '照明条件',
    zsrs string COMMENT '重伤人数',
    zyglss string COMMENT '中央隔离设施')
PARTITIONED BY
(
    ds   STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '^'
STORED AS textfile
location '/daas/motl/dwd/dwd_base_acd_file/';

-- 添加分区
alter table dwd.dwd_base_acd_file add PARTITION(ds="20230425");

-- 将数据存入到hdfs中 hdfs dfs -put dwd_base_acd_file.log /daas/motl/dwd/dwd_base_acd_file/ds=20230425

-- 检验数据 select * from dwd.dwd_base_acd_file limit 10;