CREATE EXTERNAL TABLE IF NOT EXISTS dwd.dwd_base_vio_force(
  xh string COMMENT '序号',
  pzbh string COMMENT '凭证编号',
  wsjyw string COMMENT '文书校验位',
  wslb string COMMENT '暂无',
  ryfl string COMMENT '人员分类',
  jszh string COMMENT '驾驶证号',
  dabh string COMMENT '档案编号',
  fzjg string COMMENT '发证机关',
  zjcx string COMMENT '准驾车型',
  dsr string COMMENT '当事人',
  zsxzqh string COMMENT '住所行政区划',
  zsxxdz string COMMENT '住所详细地址',
  dh string COMMENT '电话',
  lxfs string COMMENT '联系方式',
  clfl string COMMENT '车辆分类',
  hpzl string COMMENT '号牌种类',
  hphm string COMMENT '号牌号码',
  jdcsyr string COMMENT '机动车所有人',
  fdjh string COMMENT '发动机号',
  clsbdh string COMMENT '车辆识别代号',
  syxz string COMMENT '使用性质',
  jtfs string COMMENT '交通方式',
  wfsj string COMMENT '违法时间',
  xzqh string COMMENT '行政区划',
  dllx string COMMENT '道路类型',
  glxzdj string COMMENT '公路行政等级',
  wfdd string COMMENT '违法地点',
  lddm string COMMENT '路口路段代码',
  ddms string COMMENT 'ddms',
  ddjdwz string COMMENT '暂无1',
  wfdz string COMMENT '违法地址',
  wfxw1 string COMMENT '主要违法行为',
  scz1 string COMMENT '暂无2',
  bzz1 string COMMENT '暂无3',
  wfxw2 string COMMENT 'xyjjhl',
  scz2 string COMMENT 'scz2',
  bzz2 string COMMENT 'bzz2',
  wfxw3 string COMMENT '其他违法行为二',
  scz3 string COMMENT 'scz3',
  bzz3 string COMMENT 'bzz3',
  wfxw4 string COMMENT '其他违法行为三',
  scz4 string COMMENT 'scz4',
  bzz4 string COMMENT 'bzz4',
  wfxw5 string COMMENT '其他违法行为四',
  scz5 string COMMENT 'scz5',
  bzz5 string COMMENT 'bzz5',
  zqmj string COMMENT '执勤民警',
  fxjg string COMMENT '发现机关',
  fxjgmc string COMMENT '发现机关名称',
  qzcslx string COMMENT 'qzcslx',
  qtqzcs string COMMENT 'qtqzcs',
  jscjsj string COMMENT 'jscjsj',
  cjbj string COMMENT '处理标记',
  cjsj string COMMENT '处理时间',
  cljg string COMMENT '处理机关',
  cljgmc string COMMENT '处理机关名称',
  jdsbh string COMMENT '决定书编号',
  fhbj string COMMENT 'fhbj',
  fhr string COMMENT 'fhr',
  fhsj string COMMENT 'fhsj',
  jsjqbj string COMMENT '拒收拒签标记',
  jllx string COMMENT '快报记录',
  lrr string COMMENT '录入人',
  lrsj string COMMENT '录入时间',
  mjyj string COMMENT 'mjyj',
  lczt string COMMENT 'lczt',
  aqyjbj string COMMENT 'aqyjbj',
  sgdj string COMMENT '事故等级',
  cldxbj string COMMENT '处理对象标记',
  jdccldxbj string COMMENT '机动车处理对象标记',
  zdjlbj string COMMENT '转递记录标记',
  xxly string COMMENT '信息来源',
  xrms string COMMENT '写入模式',
  dkbj string COMMENT '导库标记',
  zdbj string COMMENT '转递标记',
  jsjg string COMMENT '接受机关',
  fsjg string COMMENT '发送机关',
  gxsj string COMMENT '更新时间',
  dsryy string COMMENT 'dsryy',
  bz string COMMENT '备注',
  opzbh string COMMENT 'opzbh',
  jd string COMMENT '经度',
  wd string COMMENT '纬度',
  ywjyw string COMMENT '校验位',
  zjmc string COMMENT '证件名称',
  cclzrq string COMMENT '初次领证日期',
  nl string COMMENT '年龄',
  xb string COMMENT '性别',
  hcbj string COMMENT '核查',
  ylzz1 string COMMENT '预留字段',
  ylzz2 string COMMENT '预留字段2',
  ylzz3 string COMMENT '预留字段3',
  ylzz4 string COMMENT '预留字段4',
  ylzz5 string COMMENT '预留字段5',
  ylzz6 string COMMENT '预留字段6',
  ylzz7 string COMMENT '预留字段7',
  ylzz8 string COMMENT '预留字段8',
  cjfs string COMMENT '采集方式',
  wfsj1 string COMMENT '违法时间1',
  wfdd1 string COMMENT '违法地点1',
  lddm1 string COMMENT '路口路段代码',
  ddms1 string COMMENT '地点米数',
  jsrxz string COMMENT 'jsrxz',
  clyt string COMMENT '车辆用途',
  xcfw string COMMENT '暂无5',
  dzzb string COMMENT '电子坐标',
  sfzdry string COMMENT 'sfzdry',
  xysfzmhm string COMMENT 'xysfzmhm',
  xyxm string COMMENT 'xyxm',
  ylzz11 string COMMENT '预留字段11',
  ylzz12 string COMMENT '预留字段12',
  ylzz13 string COMMENT '预留字段13',
  ylzz14 string COMMENT '预留字段14',
  ylzz15 string COMMENT '预留字段15',
  ylzz16 string COMMENT '预留字段16',
  ylzz17 string COMMENT '预留字段17',
  ylzz18 string COMMENT '预留字段18')
PARTITIONED BY
(
 ds   STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '^'
STORED AS textfile
location '/daas/motl/dwd/dwd_base_vio_force/';
-- 添加分区
alter table dwd.dwd_base_vio_force add PARTITION(ds="20230425");

-- 将数据存入到hdfs中 hdfs dfs -put dwd_base_vio_force.log /daas/motl/dwd/dwd_base_vio_force/ds=20230425

-- 检验数据 select * from dwd.dwd_base_vio_force limit 10;