CREATE EXTERNAL TABLE IF NOT EXISTS dwd.dwd_base_acd_filehuman(
  `ddzxcsfcb` string COMMENT '暂无',
  `ddzxcywbx` string COMMENT '暂无1',
  `shcd7` string COMMENT '7日内伤害程度',
  `clpp` string COMMENT '车辆品牌',
  `jyw` string COMMENT '校验位',
  `hpzl` string COMMENT '号牌种类',
  `yzwxp` string COMMENT '是否运载危险物品',
  `hcywfgbs` string COMMENT '暂无2',
  `glxzqh` string COMMENT '管理行政区划',
  `sfdsr` string COMMENT '当事人否',
  `yzbm` string COMMENT '邮政编码',
  `bxpzh` string COMMENT '保险凭证号',
  `csny` string COMMENT '出生年月',
  `fydpyw` string COMMENT 'fydpyw',
  `jdcxh` string COMMENT '机动车序号',
  `shcd24` string COMMENT '24小时内伤害程度',
  `xdzt` string COMMENT 'xdzt',
  `zsyy` string COMMENT '致死原因',
  `fzjg` string COMMENT '发证机关',
  `rylx` string COMMENT '人员类型',
  `clsyxzy` string COMMENT '车辆使用性质',
  `hphm1` string COMMENT '号牌号码1',
  `glkylc` string COMMENT '公路客运区间里程数',
  `sfty` string COMMENT '是否逃逸',
  `clxh` string COMMENT '车辆型号',
  `cclzrq` string COMMENT '初次领证日期',
  `hphm` string COMMENT '号牌号码',
  `jg` string COMMENT '机关',
  `sfcz` string COMMENT '是否超载',
  `zz` string COMMENT 'zz',
  `jl` string COMMENT '驾龄',
  `shcd` string COMMENT '伤害程度',
  `claqzk` string COMMENT '车辆安全状况',
  `jszzl` string COMMENT '驾驶证种类',
  `tdyl10` string COMMENT '特大预留10',
  `hcsfzbfhzz` string COMMENT 'hcsfzbfhzz',
  `xszt` string COMMENT '行驶状态',
  `jdcsyr` string COMMENT '机动车所有人',
  `fdjh` string COMMENT '发动机号',
  `jxmc` string COMMENT '驾校名称',
  `bx` string COMMENT '保险',
  `sfzmhm` string COMMENT '身份证明号码',
  `wfxw3` string COMMENT '其他违法行为二',
  `wfxw2` string COMMENT '其他违法行为一',
  `wfxw5` string COMMENT '其他违法行为四',
  `wfxw4` string COMMENT '其他违法行为三',
  `wfxw1` string COMMENT '主要违法行为',
  `xyjjhl` string COMMENT '血液酒精含量',
  `jdczt` string COMMENT '机动车状态',
  `hkxz` string COMMENT '户口性质',
  `shcd30` string COMMENT '30日内伤害程度',
  `wxpcyzg` string COMMENT '危险品从业资格',
  `xnyzl` string COMMENT 'xnyzl',
  `ssbw` string COMMENT '受伤部位',
  `dh` string COMMENT '电话',
  `tdyl9` string COMMENT '特大预留9',
  `ylzd1` string COMMENT '预留字段1',
  `xrzt` string COMMENT '行人状态',
  `clpp1` string COMMENT '车辆品牌1',
  `swsj` string COMMENT '死亡时间',
  `cjcxbj` string COMMENT '车驾查询标记',
  `dwgr` string COMMENT '单位个人',
  `dw` string COMMENT '单位',
  `clzxdzt` string COMMENT '车辆转向灯状态',
  `rowkey` string COMMENT 'rowkey',
  `cllx` string COMMENT '车辆类型',
  `hzl` string COMMENT '核载量1',
  `zjcx` string COMMENT '准驾车型',
  `clxh1` string COMMENT '车辆型号1',
  `sfgxqc` string COMMENT 'sfgxqc',
  `xzqh` string COMMENT '行政区划',
  `csys` string COMMENT '车身颜色',
  `jtfs` string COMMENT '交通方式',
  `yzwxphg` string COMMENT '运载危险品事故后果',
  `dabh` string COMMENT '档案编号',
  `mz` string COMMENT '民族',
  `sfdtjk` string COMMENT 'sfdtjk',
  `sgbh` string COMMENT '事故编号',
  `clhfzt` string COMMENT '车辆合法状态',
  `czclbh` string COMMENT '乘坐车辆人员编号',
  `ysxk` string COMMENT '有无危险品运输许可证',
  `cllx1` string COMMENT '车辆类型1',
  `hjz` string COMMENT '户籍地址',
  `sgzr` string COMMENT '事故责任',
  `ddzxcjgtz` string COMMENT 'ddzxcjgtz',
  `nl` string COMMENT '年龄',
  `sgzzkqnwz` string COMMENT 'sgzzkqnwz',
  `aqdtkqk` string COMMENT '安全带、头盔使用情况',
  `glkyjyfs` string COMMENT '公路客运经营方式',
  `whcd` string COMMENT '文化程度',
  `clsyxz` string COMMENT '车辆使用性质',
  `syq` string COMMENT '所有权',
  `xcjszg` string COMMENT 'xcjszg',
  `dtjksfzcyx` string COMMENT 'dtjksfzcyx',
  `ddzxcsfyhp` string COMMENT 'ddzxcsfyhp',
  `ffjg` string COMMENT '分发发证机关',
  `claqqnzt` string COMMENT '车辆安全气囊状态',
  `hpzl1` string COMMENT '号牌种类1',
  `rlzl` string COMMENT '燃料种类',
  `szl1` string COMMENT '实载量1(KG)',
  `sfxcfw` string COMMENT 'sfxcfw',
  `gj` string COMMENT '国籍',
  `szl` string COMMENT '实载量',
  `wxpzl` string COMMENT '运载危险物品种类',
  `clbsqdw` string COMMENT '车辆变速器档位',
  `hzl1` string COMMENT '核载量1(KG)',
  `pzjs` string COMMENT '碰撞中角色',
  `xb` string COMMENT '性别',
  `clfzjg` string COMMENT '车辆发证机关',
  `clsbdh` string COMMENT '车辆识别代号',
  `bxgs` string COMMENT '保险公司',
  `xrsd` string COMMENT '行人速度',
  `xm` string COMMENT '姓名',
  `rybh` string COMMENT '人员编号',
  `shcd3` string COMMENT '3日内伤害程度',
  `ytsx` string COMMENT '用途属性',
  `fsjg` string COMMENT '发送发证机关',
  `clzmdzt` string COMMENT '车辆照明灯状态',
  `zyysdw` string COMMENT '专业运输单位')
PARTITIONED BY
(
 ds   STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '^'
STORED AS textfile
location '/daas/motl/dwd/dwd_base_acd_filehuman/';

-- 添加分区
alter table dwd.dwd_base_acd_filehuman add PARTITION(ds="20230425");

-- 将数据存入到hdfs中 hdfs dfs -put dwd_base_acd_filehuman.log /daas/motl/dwd/dwd_base_acd_filehuman/ds=20230425

-- 检验数据 select * from dwd.dwd_base_acd_filehuman limit 10;