--
CREATE EXTERNAL TABLE IF NOT EXISTS dwd.dwd_base_bd_vehicle(
  `pzbh2` string COMMENT '凭证编号2',
  `pzbh1` string COMMENT '凭证编号1',
  `hpzk` string COMMENT '驾驶室后排载客人数',
  `zzcmc` string COMMENT '制造厂名称',
  `hpzl` string COMMENT '号牌种类',
  `qddjxh` string COMMENT 'qddjxh',
  `hgzbh` string COMMENT '合格证编号',
  `bpcs` string COMMENT '补领号牌次数',
  `cnzzxs` string COMMENT 'cnzzxs',
  `cyry` string COMMENT '查验人员',
  `cnzzzdl` string COMMENT 'cnzzzdl',
  `hbdbqk` string COMMENT '环保达标情况',
  `dzyx` string COMMENT '电子邮箱',
  `hdzk` string COMMENT '核定载客',
  `fzjg` string COMMENT '发证机关',
  `fzrq` string COMMENT '发证日期',
  `zzg` string COMMENT '制造国',
  `wxmbc` string COMMENT 'wxmbc',
  `yxh` string COMMENT '原机动车序号',
  `dphgzbh` string COMMENT '底盘合格证编号',
  `gcjk` string COMMENT '国产/进口',
  `zzl` string COMMENT '总质量',
  `zj` string COMMENT '轴距',
  `ccdjrq` string COMMENT '初次登记日期',
  `size` string COMMENT 'size',
  `dwbh` string COMMENT '单位编号',
  `cdqdxslcds` string COMMENT 'cdqdxslcds',
  `clxh` string COMMENT '车辆型号',
  `zqyzl` string COMMENT '准牵引总质量',
  `zs` string COMMENT '轴数',
  `jkpz` string COMMENT '进口凭证',
  `zt` string COMMENT '机动车状态',
  `hmbh` string COMMENT '后膜编号',
  `jbr` string COMMENT '经办人',
  `hphm` string COMMENT '号牌号码',
  `hdwjcd` string COMMENT 'hdwjcd',
  `xsjg` string COMMENT '销售价格',
  `xsrq` string COMMENT '销售日期',
  `sfyzhgn` string COMMENT 'sfyzhgn',
  `bdjcs` string COMMENT '补/换领证书次数',
  `jyhgbzbh` string COMMENT '检验合格标志',
  `hpqysj` string COMMENT 'hpqysj',
  `sqdm` string COMMENT '社区代码',
  `qmbh` string COMMENT '前膜编号',
  `bz` string COMMENT '备注',
  `hdzzl` string COMMENT '核定载质量',
  `sfzmhm` string COMMENT '身份证明号码',
  `xgzl` string COMMENT '相关资料',
  `ltgg` string COMMENT '轮胎规格',
  `hxnbkd` string COMMENT '货箱内部宽度',
  `syqsrq` string COMMENT 'syqsrq',
  `zbzl` string COMMENT '整备质量',
  `hxnbcd` string COMMENT '货箱内部长度',
  `fdjrq` string COMMENT '发登记证书日期',
  `clyt` string COMMENT '车辆用途',
  `cnzzzdy` string COMMENT 'cnzzzdy',
  `cnzzzl` string COMMENT 'cnzzzl',
  `djrq` string COMMENT '最近定检日期',
  `djzsbh` string COMMENT '登记证书编号',
  `xnyzl` string COMMENT 'xnyzl',
  `zxxs` string COMMENT '转向形式',
  `cnzzdtdy` string COMMENT 'cnzzdtdy',
  `cdqdxslcgk` string COMMENT 'cdqdxslcgk',
  `nszm` string COMMENT '纳税证明',
  `clpp2` string COMMENT '英文品牌',
  `gbthps` string COMMENT '钢板弹簧片数',
  `clpp1` string COMMENT '车辆品牌1',
  `yqjyqzbfqz` string COMMENT 'yqjyqzbfqz',
  `fdjxh` string COMMENT '发动机型号',
  `dzbsxlh` string COMMENT 'dzbsxlh',
  `fdjgs` string COMMENT 'fdjgs',
  `sfxny` string COMMENT 'sfxny',
  `clly` string COMMENT '1注册2转入3过户',
  `cllx` string COMMENT '车辆类型',
  `xzqh` string COMMENT '行政区划',
  `csys` string COMMENT '车身颜色',
  `qpzk` string COMMENT '驾驶室前排载客人数',
  `sjhm` string COMMENT '手机号码',
  `jkpzhm` string COMMENT '进口凭证编号',
  `dabh` string COMMENT '驾证档案编号',
  `qlj` string COMMENT '前轮距',
  `qzbfqz` string COMMENT '强制报废期止',
  `yxqz` string COMMENT '有效期止',
  `ccrq` string COMMENT '出厂日期',
  `dybj` string COMMENT '0未抵押1已抵押',
  `xszbh` string COMMENT '行驶证证芯编号',
  `fprq` string COMMENT '发牌日期',
  `nszmbh` string COMMENT '纳税证明编号',
  `ncdqsy` string COMMENT 'ncdqsy',
  `glbm` string COMMENT '管理部门',
  `gxrq` string COMMENT '更新日期',
  `lsh` string COMMENT '流水号',
  `llpz1` string COMMENT '来历凭证1',
  `qddjh` string COMMENT 'qddjh',
  `syq` string COMMENT '所有权',
  `fhgzrq` string COMMENT '发合格证日期',
  `llpz2` string COMMENT '来历凭证2',
  `syr` string COMMENT '机动车所有人',
  `zzjglx` string COMMENT 'zzjglx',
  `yqjyqz2` string COMMENT 'yqjyqz2',
  `rlzl` string COMMENT '燃料种类',
  `bxzzrq` string COMMENT '保险终止日期',
  `syxz` string COMMENT '使用性质',
  `rnum` string COMMENT 'rnum',
  `cwkc` string COMMENT '车外廓长',
  `gl` string COMMENT '功率',
  `bzcs` string COMMENT '补证次数',
  `hlj` string COMMENT '后轮距',
  `hxnbgd` string COMMENT '货箱内部高度',
  `lts` string COMMENT '轮胎数',
  `clsbdh` string COMMENT '车辆识别代号',
  `zdjzshs` string COMMENT '制登记证书行数',
  `zdyzt` string COMMENT '自定义状态',
  `xh` string COMMENT '序号',
  `zsxxdz` string COMMENT '住所详细地址',
  `xsdw` string COMMENT '销售单位',
  `ytsx` string COMMENT '用途属性',
  `hdfs` string COMMENT '获得方式',
  `cwkk` string COMMENT '车外廓宽',
  `pl` string COMMENT '排量',
  `qddjgl` string COMMENT 'qddjgl',
  `cwkg` string COMMENT '车外廓高')
PARTITIONED BY
(
 ds   STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '^'
STORED AS textfile
location '/daas/motl/dwd/dwd_base_bd_vehicle/';

alter table dwd.dwd_base_bd_vehicle add PARTITION(ds="20230425");

-- 将数据存入到hdfs中 hdfs dfs -put dwd_base_bd_vehicle.log /daas/motl/dwd/dwd_base_bd_vehicle/ds=20230425

-- 检验数据 select * from dwd.dwd_base_bd_vehicle limit 10;