-- 非现场违法表
CREATE EXTERNAL TABLE IF NOT EXISTS dwd.dwd_base_vio_surveil(
  `glxzdj` string COMMENT '公路行政等级',
  `dh` string COMMENT '电话',
  `spdz` string COMMENT '视频地址',
  `clpp` string COMMENT '车辆品牌',
  `ddms` string COMMENT '地点米数',
  `hpzl` string COMMENT '号牌种类',
  `cjjgmc` string COMMENT '采集机关名称',
  `dzzb` string COMMENT 'dzzb',
  `wfdz` string COMMENT '违法地址',
  `xrms` string COMMENT '写入模式',
  `rowkey` string COMMENT 'rowkey',
  `dkbj` string COMMENT '导库标记',
  `fzjg` string COMMENT '发证机关',
  `xzqh` string COMMENT '行政区划',
  `ylzz1` string COMMENT '预留字段',
  `bzz` string COMMENT '标准值',
  `qzclbj` string COMMENT '强制措施处理标记',
  `ylzz2` string COMMENT '预留字段2',
  `csys` string COMMENT '车身颜色',
  `jtfs` string COMMENT '交通方式',
  `jdslb` string COMMENT '决定书类别',
  `scz` string COMMENT '实测值',
  `lrr` string COMMENT '录入人',
  `zqmj` string COMMENT '执勤民警',
  `clsj` string COMMENT '处理时间',
  `lddm` string COMMENT '路口路段代码',
  `wfsj1` string COMMENT '违法时间1',
  `gxsj` string COMMENT '更新时间',
  `wfdd` string COMMENT '违法地点',
  `wfxw` string COMMENT '违法行为',
  `dllx` string COMMENT '道路类型',
  `jbr` string COMMENT '经办人',
  `hphm` string COMMENT '号牌号码',
  `wfdd1` string COMMENT '违法地点1',
  `clfl` string COMMENT '车辆分类',
  `dsr` string COMMENT '当事人',
  `xcfw` string COMMENT '暂无1',
  `cljg` string COMMENT '处理机关',
  `cjjg` string COMMENT '违法采集机关',
  `ywjyw` string COMMENT '校验位',
  `zdbj` string COMMENT '转递标记',
  `ylzz13` string COMMENT 'ylzz13',
  `wfsj` string COMMENT '违法时间',
  `ylzz12` string COMMENT 'ylzz12',
  `jdcsyr` string COMMENT '机动车所有人',
  `ylzz15` string COMMENT 'ylzz15',
  `fdjh` string COMMENT '发动机号',
  `ylzz14` string COMMENT 'ylzz14',
  `cldxbj` string COMMENT '处理对象标记',
  `ydclbj` string COMMENT '异地处理标记',
  `zdjlbj` string COMMENT '转递记录标记',
  `bz` string COMMENT '备注',
  `ylzz7` string COMMENT 'ylzz7',
  `ylzz8` string COMMENT 'ylzz8',
  `cjfs` string COMMENT '采集方式',
  `ylzz17` string COMMENT 'ylzz17',
  `ylzz16` string COMMENT 'ylzz16',
  `ylzz4` string COMMENT 'ylzz4',
  `syxz` string COMMENT '使用性质',
  `ylzz5` string COMMENT 'ylzz5',
  `clbj` string COMMENT '异地处理标记',
  `ylzz18` string COMMENT 'ylzz18',
  `ylzz6` string COMMENT 'ylzz6',
  `sbbh` string COMMENT '设备编号',
  `rnum` string COMMENT 'rnum',
  `wfbh` string COMMENT '违法编号',
  `pzbh` string COMMENT '强制措施凭证号',
  `clyt` string COMMENT 'clyt',
  `clsbdh` string COMMENT '车辆识别代号',
  `lxfs` string COMMENT '联系方式',
  `tzsh` string COMMENT '通知书号',
  `wsjyw` string COMMENT '文书校验位',
  `zsxzqh` string COMMENT '住所行政区划',
  `cljgmc` string COMMENT '处理机关名称',
  `fkje` string COMMENT '罚款金额',
  `lrsj` string COMMENT '录入时间',
  `lddm1` string COMMENT '路段代码1',
  `xh` string COMMENT '序号',
  `jkrq` string COMMENT '交款日期',
  `tzrq` string COMMENT '通知日期',
  `zsxxdz` string COMMENT '住所详细地址',
  `jsjg` string COMMENT '接受机关',
  `jkbj` string COMMENT '交款标记',
  `tzbj` string COMMENT '通知标记',
  `fsjg` string COMMENT '发送机关',
  `ddms1` string COMMENT 'ddms1',
  `jdsbh` string COMMENT '决定书编号',
  `jkfs` string COMMENT '交款方式',
  `jllx` string COMMENT '快报记录')
PARTITIONED BY
(
 ds   STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '^'
STORED AS textfile
location '/daas/motl/dwd/dwd_base_vio_surveil/';

-- 添加分区
alter table dwd.dwd_base_vio_surveil add PARTITION(ds="20230425");

-- 将数据存入到hdfs中 hdfs dfs -put dwd_base_vio_surveil.log /daas/motl/dwd/dwd_base_vio_surveil/ds=20230425

-- 检验数据 select * from dwd.dwd_base_vio_surveil limit 10;